Set local-storage
ktlyee/morph-redux-pokemon-decks pull request #15
Opened 2021-07-22 06:17 UTC by pluemthnn

**Pages added**
- Login
- Register
- Home

2021-07-29 00:13 UTC, Cijin requested changes

2021-07-29 00:13 UTC, Cijin commented on sever.ts
> +// const URL = 'http://localhost:3000/'
please remove unused code

2021-07-29 00:13 UTC, Cijin commented on src/App.tsx
> +        <NavLink className="p-2 m-3 text-white bg-blue-dark rounded-md hover:bg-blue-dark" to='/test-component'> Test Component </NavLink>
same comment as above

2021-07-29 00:13 UTC, Cijin commented on src/reducers/auth.ts
> +let user = JSON.parse(localStorage.getItem('{}')!)
this could be done in one line

```
const user = JSON.parse(localStorage.getItem('user') ?? null
```

2021-07-29 00:13 UTC, Cijin commented on src/reducers/auth.ts
> +    register(state = initialState, action: PayloadAction<object>) {
Are you checking if user exists already before you register?

2021-07-29 00:13 UTC, Cijin commented on package.json
> +    "express": "^4.17.1",
I don't see express used anywhere. Please remove unused dependencies and it's types

2021-07-29 00:13 UTC, Cijin commented on src/screens/home.tsx
> +import axios from "axios";
A good style for import statements is to import libraries at the top and leave space and then import your files
ex:

```
import React, { useState } from "react";
import axios from "axios";
import { QuestionMarkCircleIcon } from "@heroicons/react/solid";

import { Avatar, InputWithChild, Toggle, CardShow, Pagination } from "../components";
import { pokemon } from "../testComponent";
import { useAppDispatch, useAppSelector } from "../app/hooks";
import "../styles/home.css";
```
This is not a necessity but just a good convention to follow.

2021-07-29 00:13 UTC, Cijin commented on src/screens/home.tsx
> +  })
If you are merging `console.log` to the develop branch please add a comment at the top called 
```
/*
* @TODO: remove console.log statements
*/
```

This way at the end you can search your `@TODO's` for cleaning up.

2021-07-29 00:13 UTC, Cijin commented on src/screens/login.tsx
> +
Same comment as above for console.log statements

2021-07-29 00:13 UTC, Cijin commented on src/screens/login.tsx
> +                            actions.setSubmitting(false);
unused code

2021-07-29 00:13 UTC, Cijin commented on src/screens/login.tsx
> +        if(email === user.email && password === user.password) {
what about validating form values?
The form should check if the email entered is a valid email, and the password should have a min. length.
Look into `formik` docs.

https://formik.org/docs/guides/validation

2021-07-29 00:13 UTC, Cijin commented on src/screens/register.tsx
> +  const handleRegister = (values: object) => {
similar comments as the file above

2021-07-29 00:13 UTC, Cijin commented on tsconfig.json
> +  "include": ["./src", "sever.ts"]
`server`

2021-07-29 09:50 UTC, ktlyee commented on src/screens/home.tsx
> +  })
we are doing in home.tsx and this code maybe deleted

2021-07-30 02:50 UTC, Cijin approved these changes

2021-07-30 11:00 UTC, merged